module.exports.Cpu = require('./chip-8')
module.exports.Clock = require('./clock')
module.exports.Display = require('./display')
module.exports.keyboards = require('./keyboard')
module.exports.Memory = require('./memory')
module.exports.Timer = require('./timer')
module.exports.Canvas = require('./connectors/canvas.connector')
